// <auto-generated />
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PedroFranca.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Funcionarios", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("PedroFranca.Models.Folha", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("funcionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("impostoFgts")
                        .HasColumnType("REAL");

                    b.Property<float>("impostoInss")
                        .HasColumnType("REAL");

                    b.Property<float>("impostoIrrf")
                        .HasColumnType("REAL");

                    b.Property<int>("mes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantidadeHora")
                        .HasColumnType("INTEGER");

                    b.Property<float>("salarioBruto")
                        .HasColumnType("REAL");

                    b.Property<float>("salarioLiquido")
                        .HasColumnType("REAL");

                    b.Property<float>("valor")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("Folhas");
                });
#pragma warning restore 612, 618
        }
    }
}
